/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/actions": {
    /** List Actions */
    get: operations["list_actions_api_actions_get"];
    /** Add Action */
    post: operations["add_action_api_actions_post"];
  };
  "/api/actions/bulk-done": {
    /** Bulk Done */
    post: operations["bulk_done_api_actions_bulk_done_post"];
  };
  "/api/actions/bulk-reopen": {
    /** Bulk Reopen */
    post: operations["bulk_reopen_api_actions_bulk_reopen_post"];
  };
  "/api/actions/{aid}/answer": {
    /**
     * Answer
     * @description Learn the answer to a question/salary item (profile/standard_answers.yaml + the job's answers.json), then
     * mark it done. Returns the done outcome plus `learned` {key, scope, company, question, answer, match}.
     */
    post: operations["answer_api_actions__aid__answer_post"];
  };
  "/api/actions/{aid}/block-company": {
    /** Block Company */
    post: operations["block_company_api_actions__aid__block_company_post"];
  };
  "/api/actions/{aid}/done": {
    /** Done */
    post: operations["done_api_actions__aid__done_post"];
  };
  "/api/actions/{aid}/due": {
    /** Set Due */
    post: operations["set_due_api_actions__aid__due_post"];
  };
  "/api/actions/{aid}/mark-safe": {
    /** Mark Safe */
    post: operations["mark_safe_api_actions__aid__mark_safe_post"];
  };
  "/api/actions/{aid}/mark-safe/undo": {
    /** Undo Mark Safe */
    post: operations["undo_mark_safe_api_actions__aid__mark_safe_undo_post"];
  };
  "/api/actions/{aid}/reopen": {
    /** Reopen */
    post: operations["reopen_api_actions__aid__reopen_post"];
  };
  "/api/actions/{aid}/unblock-company": {
    /** Unblock Company */
    post: operations["unblock_company_api_actions__aid__unblock_company_post"];
  };
  "/api/advise": {
    /** Advise */
    get: operations["advise_api_advise_get"];
  };
  "/api/advise/{rec_id}/apply": {
    /** Advise Apply */
    post: operations["advise_apply_api_advise__rec_id__apply_post"];
  };
  "/api/batches": {
    /** Create */
    post: operations["create_api_batches_post"];
  };
  "/api/batches/{batch_id}": {
    /** Detail */
    get: operations["detail_api_batches__batch_id__get"];
  };
  "/api/contacts": {
    /** List Contacts */
    get: operations["list_contacts_api_contacts_get"];
  };
  "/api/contacts/{job_id}/{name}/mark": {
    /** Mark Contact */
    post: operations["mark_contact_api_contacts__job_id___name__mark_post"];
  };
  "/api/events": {
    /** Events */
    get: operations["events_api_events_get"];
  };
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
  "/api/inbox": {
    /** List Inbox */
    get: operations["list_inbox_api_inbox_get"];
  };
  "/api/inbox/{job_id}": {
    /** Inbox Detail */
    get: operations["inbox_detail_api_inbox__job_id__get"];
  };
  "/api/jobs": {
    /** List Jobs */
    get: operations["list_jobs_api_jobs_get"];
  };
  "/api/jobs/export": {
    /** Export */
    post: operations["export_api_jobs_export_post"];
  };
  "/api/jobs/facets": {
    /**
     * Job Facets
     * @description Distinct values of one column with counts under every other active filter (the header filter menu).
     */
    get: operations["job_facets_api_jobs_facets_get"];
  };
  "/api/jobs/tabs": {
    /** Job Tabs */
    get: operations["job_tabs_api_jobs_tabs_get"];
  };
  "/api/jobs/{job_id}": {
    /** Job Detail */
    get: operations["job_detail_api_jobs__job_id__get"];
  };
  "/api/jobs/{job_id}/failures/reset": {
    /**
     * Reset Job Failures
     * @description Clear the job's run failure count (`careeros run reset-failures`): a job out of retries runs again. Its
     * out-of-retries Action Items are marked done.
     */
    post: operations["reset_job_failures_api_jobs__job_id__failures_reset_post"];
  };
  "/api/jobs/{job_id}/files/{name}": {
    /** Job File */
    get: operations["job_file_api_jobs__job_id__files__name__get"];
  };
  "/api/jobs/{job_id}/open-folder": {
    /** Open Folder */
    post: operations["open_folder_api_jobs__job_id__open_folder_post"];
  };
  "/api/jobs/{job_id}/override": {
    /** Set Override */
    post: operations["set_override_api_jobs__job_id__override_post"];
  };
  "/api/jobs/{job_id}/pipeline": {
    /**
     * Job Pipeline
     * @description The job's stage, the one next action (Start / Continue / Approve & continue), why it is blocked, what a
     * needs_review job waits on, and the running run that names it.
     */
    get: operations["job_pipeline_api_jobs__job_id__pipeline_get"];
    /**
     * Start Job Pipeline
     * @description Run the job's next stage as a detached `careeros run <kind> --job <id>`; approve_continue first moves
     * needs_review -> queued. 409 when a run is active or paused, or the job is not runnable (Tier A never applies).
     */
    post: operations["start_job_pipeline_api_jobs__job_id__pipeline_post"];
  };
  "/api/jobs/{job_id}/qa": {
    /** Rerun Qa */
    post: operations["rerun_qa_api_jobs__job_id__qa_post"];
  };
  "/api/jobs/{job_id}/safety/clear": {
    /** Safety Clear */
    post: operations["safety_clear_api_jobs__job_id__safety_clear_post"];
  };
  "/api/jobs/{job_id}/safety/flag": {
    /** Safety Flag */
    post: operations["safety_flag_api_jobs__job_id__safety_flag_post"];
  };
  "/api/jobs/{job_id}/safety/verify": {
    /** Safety Verify */
    post: operations["safety_verify_api_jobs__job_id__safety_verify_post"];
  };
  "/api/jobs/{job_id}/status": {
    /** Set Status */
    post: operations["set_status_api_jobs__job_id__status_post"];
  };
  "/api/jobs/{job_id}/submitted": {
    /** Mark Submitted */
    post: operations["mark_submitted_api_jobs__job_id__submitted_post"];
  };
  "/api/jobs/{job_id}/withdraw": {
    /** Withdraw */
    post: operations["withdraw_api_jobs__job_id__withdraw_post"];
  };
  "/api/learning/lessons": {
    /** List Lessons */
    get: operations["list_lessons_api_learning_lessons_get"];
    /** Add Lesson */
    post: operations["add_lesson_api_learning_lessons_post"];
  };
  "/api/meta": {
    /** Meta */
    get: operations["meta_api_meta_get"];
  };
  "/api/pipeline": {
    /** Board */
    get: operations["board_api_pipeline_get"];
  };
  "/api/prune": {
    /** Prune */
    post: operations["prune_api_prune_post"];
  };
  "/api/runs": {
    /** History */
    get: operations["history_api_runs_get"];
    /**
     * Start
     * @description A score or prepare batch; `dry_run` returns the selection and starts nothing.
     */
    post: operations["start_api_runs_post"];
  };
  "/api/runs/cancel": {
    /** Cancel */
    post: operations["cancel_api_runs_cancel_post"];
  };
  "/api/runs/catch-up": {
    /** Catch Up */
    post: operations["catch_up_api_runs_catch_up_post"];
  };
  "/api/runs/current": {
    /** Current */
    get: operations["current_api_runs_current_get"];
  };
  "/api/runs/pause": {
    /** Pause */
    post: operations["pause_api_runs_pause_post"];
  };
  "/api/runs/queue/{kind}": {
    /** Queue */
    get: operations["queue_api_runs_queue__kind__get"];
  };
  "/api/runs/resume": {
    /** Resume */
    post: operations["resume_api_runs_resume_post"];
  };
  "/api/runs/steps/{kind}": {
    /** Start Step */
    post: operations["start_step_api_runs_steps__kind__post"];
  };
  "/api/runs/{run_id}": {
    /** Detail */
    get: operations["detail_api_runs__run_id__get"];
  };
  "/api/runs/{run_id}/stream": {
    /**
     * Stream
     * @description SSE: `event` frames ({type, text, attempt?}) from the attempt streams and run.log, then one `end` frame
     * ({state, stop_reason}) when the run is no longer running. A reconnect replays from the start.
     */
    get: operations["stream_api_runs__run_id__stream_get"];
  };
  "/api/schedule": {
    /** Schedule */
    get: operations["schedule_api_schedule_get"];
  };
  "/api/schedule/{action}": {
    /** Schedule Action */
    post: operations["schedule_action_api_schedule__action__post"];
  };
  "/api/settings": {
    /** Sections */
    get: operations["sections_api_settings_get"];
  };
  "/api/settings/runs/ranking-preview": {
    /** Ranking Preview */
    post: operations["ranking_preview_api_settings_runs_ranking_preview_post"];
  };
  "/api/settings/{section}": {
    /** Read */
    get: operations["read_api_settings__section__get"];
    /** Save */
    put: operations["save_api_settings__section__put"];
  };
  "/api/settings/{section}/diff": {
    /** Diff */
    post: operations["diff_api_settings__section__diff_post"];
  };
  "/api/settings/{section}/reset/{group}": {
    /** Reset */
    post: operations["reset_api_settings__section__reset__group__post"];
  };
  "/api/status": {
    /** Status */
    get: operations["status_api_status_get"];
  };
  "/api/storage": {
    /** Storage */
    get: operations["storage_api_storage_get"];
  };
  "/api/today": {
    /** Today */
    get: operations["today_api_today_get"];
  };
  "/api/tracker/open": {
    /** Open Tracker */
    post: operations["open_tracker_api_tracker_open_post"];
  };
  "/api/tracker/sync": {
    /** Sync */
    post: operations["sync_api_tracker_sync_post"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ActionCounts */
    ActionCounts: {
      /** Done */
      done: number;
      /** Open */
      open: number;
      /** Today */
      today: number;
    };
    /** ActionGroup */
    ActionGroup: {
      /** Count */
      count: number;
      /** Items */
      items: components["schemas"]["ActionItem"][];
      /** Key */
      key: string;
    };
    /** ActionHead */
    ActionHead: {
      /** Overdue */
      overdue: number;
      /** Soon */
      soon: number;
    };
    /** ActionHint */
    ActionHint: {
      /** Due */
      due: string | null;
      /** Due Reason */
      due_reason: string | null;
      /**
       * Kind
       * @constant
       */
      kind: "action";
      /** Type */
      type: string;
    };
    /**
     * ActionItem
     * @description One Action Item as /api/actions and Today's "Needs you" list return it (the OpenAPI shape).
     */
    ActionItem: {
      /** Bucket */
      bucket: string;
      /** Company */
      company: string;
      /** Created */
      created: string | null;
      /** Detail */
      detail: string | null;
      /** Done */
      done: boolean;
      /** Done Date */
      done_date: string | null;
      /** Due */
      due: string | null;
      /** Due Date Only */
      due_date_only: boolean;
      /** Due Reason */
      due_reason: string | null;
      /** Id */
      id: string;
      /** Job Id */
      job_id: string | null;
      /** Level */
      level: string;
      /** Link */
      link: string;
      /** Needs */
      needs: string;
      /** Priority */
      priority: string;
      /** Role */
      role: string;
      /** Scam Actions */
      scam_actions: boolean;
      /** Type */
      type: string;
      /** What */
      what: string;
    };
    /** ActionRow */
    ActionRow: {
      /** Company */
      company: string | null;
      /** Created */
      created: string | null;
      /** Id */
      id: string;
      /** Job Id */
      job_id: string | null;
      /** Link */
      link: string | null;
      /** Needs */
      needs: string | null;
      /** Priority */
      priority: string | null;
      /** Role */
      role: string | null;
      /** Type */
      type: string | null;
      /** What */
      what: string | null;
    };
    /** ActionsPage */
    ActionsPage: {
      counts: components["schemas"]["ActionCounts"];
      /** Group */
      group: string;
      /** Groups */
      groups: components["schemas"]["ActionGroup"][];
      head: components["schemas"]["ActionHead"];
      /** More Done */
      more_done: number;
      /** Now */
      now: string;
      /** Sort */
      sort: string;
      /** Tab */
      tab: string;
    };
    /** ActivityEntry */
    ActivityEntry: {
      /** At */
      at: string;
      /** Component */
      component: string;
      /** Label */
      label: string;
      /** Message */
      message: string;
    };
    /**
     * Advice
     * @description GET /api/advise: storage and run advice plus every recommendation (storage first).
     */
    Advice: {
      /** Recommendations */
      recommendations: components["schemas"]["Recommendation"][];
      runs: components["schemas"]["RunsAdvice"];
      storage: components["schemas"]["StorageAdvice"];
    };
    /** AdvisorConfig */
    AdvisorConfig: {
      advisor: components["schemas"]["AdvisorLimits"];
      storage: components["schemas"]["StorageLimits"];
    };
    /** AdvisorLimits */
    AdvisorLimits: {
      /** Advise After Days */
      advise_after_days: number;
      /** Failure Rate Warn */
      failure_rate_warn: number;
      /** Min Runs */
      min_runs: number;
      /** Prune Idle Weeks */
      prune_idle_weeks: number;
      /** Usage Limit Stops */
      usage_limit_stops: number;
      /** Window Days */
      window_days: number;
    };
    /** Answer */
    Answer: {
      /** Answer */
      answer: string;
      /** Company */
      company?: string | null;
      /**
       * Scope
       * @default general
       */
      scope?: string;
    };
    /** AppliedWeekTile */
    AppliedWeekTile: {
      /** Daily Cap */
      daily_cap: number | null;
      /** Rows */
      rows: components["schemas"]["TileRow"][];
      /** Since */
      since: string;
      /** Value */
      value: number;
    };
    /** Attempt */
    Attempt: {
      /** Company */
      company?: string | null;
      /** Detail */
      detail?: string;
      /** Duration S */
      duration_s?: number | null;
      /** Ended At */
      ended_at?: string | null;
      /** Headless */
      headless?: {
        [key: string]: unknown;
      };
      /** Job Id */
      job_id: string | null;
      /** N */
      n: number;
      /** Outcome */
      outcome: string;
      /** Rank */
      rank?: number | null;
      /** Result */
      result?: {
        [key: string]: unknown;
      } | null;
      /** Run Id */
      run_id?: string;
      /** Session Id */
      session_id?: string | null;
      /** Stage */
      stage?: string;
      /** Started At */
      started_at?: string | null;
      /** Stream */
      stream?: string;
      /** Title */
      title?: string | null;
      /** Why */
      why?: string | null;
    };
    /** Batch */
    Batch: {
      /** Created At */
      created_at?: string | null;
      /** Dry Run */
      dry_run: boolean;
      /** Excluded */
      excluded: components["schemas"]["Excluded"][];
      /** Id */
      id?: string | null;
      /** Kind */
      kind: string;
      /** Name */
      name?: string | null;
      /** Selected */
      selected: components["schemas"]["BatchJob"][];
      /** Status */
      status?: string | null;
      /** Stop At */
      stop_at: string;
    };
    /** BatchJob */
    BatchJob: {
      /** Auto Submit */
      auto_submit: boolean;
      /** Company */
      company: string;
      /** Fit */
      fit?: number | null;
      /** Job Id */
      job_id: string;
      /** Rank */
      rank: number;
      /** Score */
      score: number;
      /** Stage */
      stage: string;
      /** Stages */
      stages: string[];
      /** State */
      state?: string | null;
      /** Status */
      status: string;
      /** Submit Reason */
      submit_reason: string;
      /** Title */
      title: string;
      /** Why */
      why: string;
    };
    /** Board */
    Board: {
      /** Applications */
      applications: components["schemas"]["Card"][];
      closed: components["schemas"]["Closed"];
      /** Funnel */
      funnel: components["schemas"]["FunnelStage"][];
      options: components["schemas"]["BoardOptions"];
      submitted: components["schemas"]["Submitted"];
    };
    /** BoardOptions */
    BoardOptions: {
      /** Categories */
      categories: string[];
      /** Locations */
      locations: components["schemas"]["LocationOption"][];
    };
    /** CancelBody */
    CancelBody: {
      /** Run Id */
      run_id?: string | null;
    };
    /** Card */
    Card: {
      /** Category */
      category: string | null;
      /** Company */
      company: string | null;
      /** Fit */
      fit: number | null;
      /** Found At */
      found_at: string | null;
      /** Hint */
      hint: components["schemas"]["ActionHint"] | components["schemas"]["SafetyHint"] | components["schemas"]["NotScoredHint"] | components["schemas"]["TierAHint"] | components["schemas"]["QaFailedHint"] | null;
      /** Job Id */
      job_id: string;
      /** Location */
      location: string | null;
      /** Override */
      override: string | null;
      /** Qa Passed */
      qa_passed: boolean | null;
      /** Qa Score */
      qa_score: number | null;
      /** Safety */
      safety: string | null;
      /** Status */
      status: string;
      /** Tier */
      tier: string | null;
      /** Title */
      title: string | null;
      /** Updated At */
      updated_at: string | null;
    };
    /** CatchUp */
    CatchUp: {
      /** Created At */
      created_at: string;
      /** Kinds */
      kinds: {
        [key: string]: components["schemas"]["CatchUpKind"];
      };
      /** Updated At */
      updated_at?: string;
    };
    /** CatchUpBody */
    CatchUpBody: {
      /**
       * Dismiss
       * @default false
       */
      dismiss?: boolean;
    };
    /** CatchUpKind */
    CatchUpKind: {
      /** First Missed */
      first_missed: string | null;
      /** Last Missed */
      last_missed?: string | null;
      /** Slots */
      slots: number;
    };
    /** Changes */
    Changes: {
      /** Changes */
      changes?: {
        [key: string]: unknown;
      };
      /** Version */
      version?: string | null;
    };
    /** ClearBody */
    ClearBody: {
      /**
       * Note
       * @default
       */
      note?: string;
    };
    /** Closed */
    Closed: {
      /** By Status */
      by_status: {
        [key: string]: number;
      };
      /** Count */
      count: number;
    };
    /** ClosedCount */
    ClosedCount: {
      /** By Status */
      by_status: {
        [key: string]: number;
      };
      /** Count */
      count: number;
    };
    /** ColumnConfig */
    ColumnConfig: {
      /** Name */
      name: string;
      /** Statuses */
      statuses: string[];
    };
    /** ContactPolicy */
    ContactPolicy: {
      /** Detail */
      detail: string;
      /** Manual */
      manual: boolean;
      /** Name */
      name: string;
      /** Reason */
      reason: string | null;
      /** Role */
      role: string;
    };
    /** ContactRow */
    ContactRow: {
      /** Company */
      company: string | null;
      draft: components["schemas"]["InboxDraft"] | null;
      /** Email */
      email: string | null;
      /** Email Confidence */
      email_confidence: string | null;
      /** Job Id */
      job_id: string;
      /** Job Status */
      job_status: string | null;
      /** Job Title */
      job_title: string | null;
      /** Linkedin */
      linkedin: string | null;
      /** Linkedin Degree */
      linkedin_degree: number | null;
      /** Manual */
      manual: boolean;
      /** Manual Detail */
      manual_detail: string | null;
      /** Manual Reason */
      manual_reason: string | null;
      /** Mode */
      mode: string;
      /** Mutuals */
      mutuals: number | null;
      /** Name */
      name: string;
      /** Replied */
      replied: string | null;
      /** Sent */
      sent: boolean;
      /** Title */
      title: string;
    };
    /** ContactsPage */
    ContactsPage: {
      /** Items */
      items: components["schemas"]["ContactRow"][];
      /** Linkedin Drafts */
      linkedin_drafts: number;
      policy: components["schemas"]["ContactsPolicy"];
    };
    /** ContactsPolicy */
    ContactsPolicy: {
      /** Manual If Connected */
      manual_if_connected: boolean;
      /** Manual If Mutuals */
      manual_if_mutuals: boolean;
    };
    /** Counts */
    Counts: {
      /** Action Items Open */
      action_items_open: number;
      /** Contacts */
      contacts: number;
      /** Inbox */
      inbox: number;
      /** Jobs */
      jobs: number;
    };
    /** CreateBody */
    CreateBody: {
      /**
       * Dry Run
       * @default false
       */
      dry_run?: boolean;
      /** Job Ids */
      job_ids: string[];
      /** Name */
      name?: string | null;
      /**
       * Stop At
       * @enum {string}
       */
      stop_at: "score" | "prepare" | "fill" | "submit";
    };
    /** CurrentRun */
    CurrentRun: {
      /** Attempts */
      attempts: components["schemas"]["Attempt"][];
      budget?: components["schemas"]["RunBudget"];
      cap: components["schemas"]["RunCap"] | null;
      /** Cmd */
      cmd?: string[];
      /** Counters */
      counters?: {
        [key: string]: number;
      };
      /** Current Job */
      current_job: string | null;
      /** Detail */
      detail?: string;
      /** Dry Run */
      dry_run?: boolean;
      /** Duration S */
      duration_s?: number | null;
      /** Ended At */
      ended_at: string | null;
      /** Holder */
      holder: {
        [key: string]: unknown;
      } | null;
      /** Id */
      id: string;
      /** Jobs */
      jobs: components["schemas"]["RunJobRow"][];
      /** Kind */
      kind: string;
      /** Pid */
      pid?: number | null;
      /** Scheduled */
      scheduled: boolean;
      /** Started At */
      started_at: string | null;
      /** State */
      state: string;
      /** Status */
      status: string;
      /** Step */
      step?: boolean;
      /** Stop Reason */
      stop_reason: string | null;
      /** Trigger */
      trigger: string;
      used: components["schemas"]["RunUsed"];
      /** Warnings */
      warnings?: string[];
    };
    /** DiskUsage */
    DiskUsage: {
      /** Free */
      free: number;
      /** Free Pct */
      free_pct: number;
      /** Total */
      total: number;
    };
    /** Due */
    Due: {
      /** Due */
      due?: string | null;
      /** Due Reason */
      due_reason?: string | null;
    };
    /** Excluded */
    Excluded: {
      /** Job Id */
      job_id: string;
      /** Reason */
      reason: string;
    };
    /** Export */
    Export: {
      /** Applied From */
      applied_from?: string | null;
      /** Applied To */
      applied_to?: string | null;
      /**
       * Ats
       * @default []
       */
      ats?: string[];
      /**
       * Category
       * @default []
       */
      category?: string[];
      /** Closes From */
      closes_from?: string | null;
      /** Closes To */
      closes_to?: string | null;
      /** Columns */
      columns?: string[] | null;
      /**
       * Company
       * @default []
       */
      company?: string[];
      /** Fit Max */
      fit_max?: number | null;
      /** Fit Min */
      fit_min?: number | null;
      /** Found From */
      found_from?: string | null;
      /** Found To */
      found_to?: string | null;
      /** Job Ids */
      job_ids?: string[] | null;
      /** Location */
      location?: string | null;
      /**
       * Location In
       * @default []
       */
      location_in?: string[];
      /** Q */
      q?: string | null;
      /**
       * Qa Passed
       * @default []
       */
      qa_passed?: string[];
      /** Qa Score Max */
      qa_score_max?: number | null;
      /** Qa Score Min */
      qa_score_min?: number | null;
      /**
       * Safety
       * @default []
       */
      safety?: string[];
      /**
       * Sort
       * @default -fit
       */
      sort?: string;
      /**
       * Status
       * @default []
       */
      status?: string[];
      /** Tab */
      tab?: string | null;
      /**
       * Tier
       * @default []
       */
      tier?: string[];
    };
    /** FacetValue */
    FacetValue: {
      /** Count */
      count: number;
      /** Value */
      value: string | number | null;
    };
    /** FailureInfo */
    FailureInfo: {
      /** Count */
      count: number;
      /** Excluded */
      excluded: boolean;
      /** Kind */
      kind: string;
      /** Last Detail */
      last_detail: string | null;
      /** Last Outcome */
      last_outcome: string | null;
      /** Last Run */
      last_run: string | null;
      /** Max Attempts */
      max_attempts: number;
    };
    /** FieldSchema */
    FieldSchema: {
      /** Control */
      control: string;
      /** Default */
      default: unknown;
      /** File */
      file: string;
      /** Help */
      help: string;
      /** Id */
      id: string;
      /** Integer */
      integer: boolean;
      /** Key */
      key: string;
      /** Label */
      label: string;
      /** Locked */
      locked: boolean;
      /** Max */
      max: number | null;
      /** Min */
      min: number | null;
      /** Note */
      note: string;
      /** Nullable */
      nullable: boolean;
      /** Options */
      options: unknown[];
      /** Personal */
      personal: boolean;
      /** Readonly */
      readonly: boolean;
      /** Recommended */
      recommended: boolean;
      /** Step */
      step: number | null;
      /** Strict Options */
      strict_options: boolean;
      /** Unit */
      unit: string;
    };
    /** FileEntry */
    FileEntry: {
      /** Modified */
      modified: number;
      /** Name */
      name: string;
      /** Size */
      size: number;
    };
    /** FlagBody */
    FlagBody: {
      /**
       * Confidence
       * @default high
       * @enum {string}
       */
      confidence?: "high" | "medium";
      /**
       * Evidence
       * @default []
       */
      evidence?: string[];
      /**
       * Notes
       * @default
       */
      notes?: string;
      /**
       * Reason
       * @default
       */
      reason?: string;
    };
    /** FunnelStage */
    FunnelStage: {
      /** Count */
      count: number;
      /** Status */
      status: string;
    };
    /** GroupSchema */
    GroupSchema: {
      /** Help */
      help: string;
      /** Id */
      id: string;
      /** Items */
      items: (components["schemas"]["PolicyItem"] | components["schemas"]["FieldSchema"])[];
      /** Title */
      title: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HistoryPage */
    HistoryPage: {
      /** Next Cursor */
      next_cursor: string | null;
      /** Runs */
      runs: components["schemas"]["RunRecord"][];
    };
    /** Ids */
    Ids: {
      /** Ids */
      ids: string[];
    };
    /** InboxAvailability */
    InboxAvailability: {
      /** Available */
      available: boolean;
      /** Reason */
      reason: string;
    };
    /** InboxDetail */
    InboxDetail: {
      /** Applied At */
      applied_at: string | null;
      /** Company */
      company: string | null;
      /** Days Since Applied */
      days_since_applied: number | null;
      /** Drafts */
      drafts: components["schemas"]["InboxDraft"][];
      /** Job Id */
      job_id: string;
      last_email: components["schemas"]["InboxEmail"] | null;
      next: components["schemas"]["InboxNext"];
      /** Placeholders */
      placeholders: number;
      /** Primary */
      primary: number | null;
      sending: components["schemas"]["InboxAvailability"];
      /** Status */
      status: string;
      sync: components["schemas"]["InboxAvailability"];
      /** Thread */
      thread: components["schemas"]["InboxThreadEvent"][];
      /** Tier */
      tier: string | null;
      /** Title */
      title: string | null;
      /** Updated At */
      updated_at: string | null;
    };
    /** InboxDraft */
    InboxDraft: {
      /** Body */
      body: string;
      /** Channel */
      channel: string;
      /** Contact */
      contact: string;
      /** Due */
      due: string | null;
      /** Followup */
      followup: boolean;
      /** Kind */
      kind: string;
      /** Linkedin Message */
      linkedin_message: string | null;
      /** Linkedin Note */
      linkedin_note: string | null;
      /** Manual Reason */
      manual_reason: string | null;
      /** Manual Tailor */
      manual_tailor: boolean;
      /** Mode */
      mode: string;
      /** Placeholders */
      placeholders: string[];
      /** Role */
      role: string;
      /** Sent */
      sent: boolean;
      /** Sent By */
      sent_by: string | null;
      /** Sent Date */
      sent_date: string | null;
      /** Subject */
      subject: string | null;
      /** To */
      to: string | null;
      /** Verified */
      verified: boolean;
      /** Words */
      words: number;
    };
    /** InboxEmail */
    InboxEmail: {
      /** At */
      at: string | null;
      /** Class */
      class: string;
      /** From */
      from: string;
      /** Link */
      link: string | null;
      /** Status */
      status: string;
    };
    /** InboxNext */
    InboxNext: {
      /** Due */
      due: string | null;
      /** Kind */
      kind: string;
      /** Mode */
      mode: string;
    };
    /** InboxPage */
    InboxPage: {
      /** Items */
      items: components["schemas"]["InboxRow"][];
      /** Last Sync */
      last_sync: string | null;
      sending: components["schemas"]["InboxAvailability"];
      sync: components["schemas"]["InboxAvailability"];
    };
    /** InboxRow */
    InboxRow: {
      /** Applied At */
      applied_at: string | null;
      /** Company */
      company: string | null;
      /** Days Since Applied */
      days_since_applied: number | null;
      /** Drafts */
      drafts: number;
      /** Job Id */
      job_id: string;
      last_email: components["schemas"]["InboxEmail"] | null;
      next: components["schemas"]["InboxNext"];
      /** Placeholders */
      placeholders: number;
      /** Status */
      status: string;
      /** Tier */
      tier: string | null;
      /** Title */
      title: string | null;
      /** Updated At */
      updated_at: string | null;
    };
    /** InboxThreadEvent */
    InboxThreadEvent: {
      /** At */
      at: string;
      /** Class */
      class?: string;
      /** Contact */
      contact?: string;
      /** From */
      from?: string;
      /** Kind */
      kind?: string;
      /** Link */
      link?: string | null;
      /** Note */
      note?: string | null;
      /** Sent By */
      sent_by?: string | null;
      /** Status */
      status?: string | null;
      /** Type */
      type: string;
    };
    /** IndexState */
    IndexState: {
      /** Indexed At */
      indexed_at: string | null;
    };
    /** InterviewsTile */
    InterviewsTile: {
      /** Rows */
      rows: components["schemas"]["TileRow"][];
      /** Value */
      value: number;
    };
    /** JobDetail */
    JobDetail: {
      /** Activity */
      activity: components["schemas"]["ActivityEntry"][];
      /** Apply Session */
      apply_session: {
        [key: string]: unknown;
      } | null;
      /** Contacts */
      contacts: {
          [key: string]: unknown;
        }[];
      /** Contacts Policy */
      contacts_policy: components["schemas"]["ContactPolicy"][];
      /** Documents */
      documents: components["schemas"]["FileEntry"][];
      /** History */
      history: {
          [key: string]: unknown;
        }[];
      job: components["schemas"]["JobRow"] | null;
      /** Log */
      log: string;
      /** Other Files */
      other_files: components["schemas"]["FileEntry"][];
      /** Outreach */
      outreach: {
        [key: string]: unknown;
      } | null;
      /** Override */
      override: string | null;
      /** Posting */
      posting: {
        [key: string]: unknown;
      };
      /** Qa */
      qa: {
        [key: string]: unknown;
      } | null;
      registry: components["schemas"]["Registry"];
      /** Safety */
      safety: {
        [key: string]: unknown;
      } | null;
      /** Score */
      score: {
        [key: string]: unknown;
      } | null;
      /** Screenshots */
      screenshots: components["schemas"]["FileEntry"][];
      /** Status */
      status: string | null;
      /** Submitted */
      submitted: string[];
    };
    /** JobFacets */
    JobFacets: {
      /** Field */
      field: string;
      /** Values */
      values: components["schemas"]["FacetValue"][];
    };
    /** JobListItem */
    JobListItem: {
      /** Applied At */
      applied_at: string | null;
      /** Ats */
      ats: string | null;
      /** Category */
      category: string | null;
      /** Closes At */
      closes_at: string | null;
      /** Company */
      company: string | null;
      /** Fit */
      fit: number | null;
      /** Found At */
      found_at: string | null;
      /** Job Id */
      job_id: string;
      /** Location */
      location: string | null;
      /** Next Action */
      next_action: string | null;
      /** Qa Passed */
      qa_passed: number | null;
      /** Qa Score */
      qa_score: number | null;
      /** Safety */
      safety: string | null;
      /** Status */
      status: string | null;
      /** Tier */
      tier: string | null;
      /** Title */
      title: string | null;
      /** Updated At */
      updated_at: string | null;
      /** Url */
      url: string | null;
    };
    /** JobRow */
    JobRow: {
      /** Applied At */
      applied_at: string | null;
      /** Ats */
      ats: string | null;
      /** Category */
      category: string | null;
      /** Closes At */
      closes_at: string | null;
      /** Company */
      company: string | null;
      /** Fit */
      fit: number | null;
      /** Found At */
      found_at: string | null;
      /** Job Id */
      job_id: string;
      /** Location */
      location: string | null;
      /** Qa Passed */
      qa_passed: number | null;
      /** Qa Score */
      qa_score: number | null;
      /** Safety */
      safety: string | null;
      /** Status */
      status: string | null;
      /** Tier */
      tier: string | null;
      /** Title */
      title: string | null;
      /** Updated At */
      updated_at: string | null;
      /** Url */
      url: string | null;
    };
    /** JobStep */
    JobStep: {
      /** Name */
      name: string;
      /**
       * State
       * @enum {string}
       */
      state: "done" | "active" | "pending" | "skipped";
    };
    /** JobsPage */
    JobsPage: {
      /** Items */
      items: components["schemas"]["JobListItem"][];
      /** Next Cursor */
      next_cursor: string | null;
      /** Total */
      total: number;
    };
    /** JobsTab */
    JobsTab: {
      /** Count */
      count: number;
      /** Key */
      key: string;
      /** Label */
      label: string;
    };
    /** JobsTabs */
    JobsTabs: {
      /** Tabs */
      tabs: components["schemas"]["JobsTab"][];
    };
    /** Lesson */
    Lesson: {
      /** Added */
      added?: string | null;
      /** Ats */
      ats?: string | null;
      /** Company */
      company?: string | null;
      /** Id */
      id: string;
      /** Job Id */
      job_id?: string | null;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
      /** Text */
      text: string;
    };
    /** Lessons */
    Lessons: {
      /** Lessons */
      lessons: components["schemas"]["Lesson"][];
    };
    /** LocationOption */
    LocationOption: {
      /** Count */
      count: number;
      /** Value */
      value: string;
    };
    /** MarkBody */
    MarkBody: {
      /** Degree */
      degree?: number | null;
      /** Mutuals */
      mutuals?: number | null;
    };
    /** Meta */
    Meta: {
      /** Action Needs */
      action_needs: string[];
      /** Action Types */
      action_types: string[];
      /** Clean Stops */
      clean_stops: string[];
      pipeline: components["schemas"]["PipelineConfig"];
      presets: components["schemas"]["Presets"];
      /** Priorities */
      priorities: string[];
      /** Safety Verdicts */
      safety_verdicts: string[];
      /** Statuses */
      statuses: string[];
      /** Stop Reasons */
      stop_reasons: string[];
      /** Tiers */
      tiers: string[];
      ui: components["schemas"]["UiSettings"];
    };
    /** NeedsYouTile */
    NeedsYouTile: {
      /** High */
      high: number;
      /** Rows */
      rows: components["schemas"]["ActionRow"][];
      /** Value */
      value: number;
    };
    /** NewItem */
    NewItem: {
      /**
       * Company
       * @default
       */
      company?: string;
      /** Due */
      due?: string | null;
      /** Due Reason */
      due_reason?: string | null;
      /**
       * Job Id
       * @default
       */
      job_id?: string;
      /**
       * Link
       * @default
       */
      link?: string;
      /**
       * Needs
       * @default anytime
       */
      needs?: string;
      /**
       * Priority
       * @default M
       */
      priority?: string;
      /**
       * Role
       * @default
       */
      role?: string;
      /**
       * Type
       * @default other
       */
      type?: string;
      /** What */
      what: string;
    };
    /** NewLesson */
    NewLesson: {
      /** Ats */
      ats?: string | null;
      /** Company */
      company?: string | null;
      /** Job Id */
      job_id?: string | null;
      /**
       * Tags
       * @default []
       */
      tags?: string[];
      /** Text */
      text: string;
    };
    /** NotScoredHint */
    NotScoredHint: {
      /**
       * Kind
       * @constant
       */
      kind: "not_scored";
    };
    /** NoteBody */
    NoteBody: {
      /** Note */
      note?: string | null;
    };
    /** OverrideBody */
    OverrideBody: {
      /** Value */
      value: string;
    };
    /** PauseBody */
    PauseBody: {
      /**
       * Reason
       * @default
       */
      reason?: string;
      /** Until */
      until?: string | null;
    };
    /** PipelineBody */
    PipelineBody: {
      /**
       * Action
       * @enum {string}
       */
      action: "start" | "continue" | "approve_continue";
      /**
       * Force
       * @default false
       */
      force?: boolean;
    };
    /** PipelineColumnCount */
    PipelineColumnCount: {
      /** Count */
      count: number;
      /** Name */
      name: string;
      /** Statuses */
      statuses: string[];
    };
    /** PipelineConfig */
    PipelineConfig: {
      /** Card Limit */
      card_limit: number;
      /** Closed */
      closed: string[];
      /** Columns */
      columns: components["schemas"]["ColumnConfig"][];
    };
    /** PipelineCounts */
    PipelineCounts: {
      closed: components["schemas"]["ClosedCount"];
      /** Columns */
      columns: components["schemas"]["PipelineColumnCount"][];
    };
    /** PipelineStarted */
    PipelineStarted: {
      /** Kind */
      kind: string;
      /** Run Id */
      run_id: string;
    };
    /** PipelineState */
    PipelineState: {
      /** Active Run Id */
      active_run_id: string | null;
      /** Auto Submit */
      auto_submit: boolean;
      /** Blocked Reason */
      blocked_reason: string | null;
      failures: components["schemas"]["FailureInfo"] | null;
      /** Force */
      force: boolean;
      /** Next Action */
      next_action: ("start" | "continue" | "approve_continue") | null;
      /** Next Kind */
      next_kind: string | null;
      /** Next Label */
      next_label: string | null;
      /** Note */
      note: string | null;
      /** Queued In Run */
      queued_in_run: string | null;
      /** Review Reasons */
      review_reasons: components["schemas"]["Reason"][];
      /** Stage */
      stage: string;
    };
    /**
     * PolicyItem
     * @description A locked row: a rule the code enforces whatever the config says.
     */
    PolicyItem: {
      /**
       * Control
       * @constant
       */
      control: "policy";
      /** Label */
      label: string;
      /**
       * Locked
       * @constant
       */
      locked: true;
      /** Value */
      value: string;
      /** Why */
      why: string;
    };
    /** PrepareQueue */
    PrepareQueue: {
      /** Error */
      error: string | null;
      /** Total */
      total: number | null;
    };
    /** Presets */
    Presets: {
      /** Current */
      current: string;
      /** Names */
      names: string[];
      /** Recommended */
      recommended: string;
      /** Values */
      values: {
        [key: string]: {
          [key: string]: number;
        };
      };
    };
    /** Preview */
    Preview: {
      /**
       * Kind
       * @default score
       */
      kind?: string;
      /** Weights */
      weights?: {
        [key: string]: unknown;
      };
    };
    /** Projection */
    Projection: {
      /** 30D */
      "30d": number;
      /** 90D */
      "90d": number;
    };
    /** PruneBody */
    PruneBody: {
      /**
       * Dry Run
       * @default true
       */
      dry_run?: boolean;
    };
    /** QaFailedHint */
    QaFailedHint: {
      /**
       * Kind
       * @constant
       */
      kind: "qa_failed";
    };
    /** QuietHours */
    QuietHours: {
      /** End */
      end: string;
      /** Start */
      start: string;
    };
    /**
     * Reason
     * @description Why a job needs a human. `code`: stable id the UI may map; `text`: a human sentence (no commands, no internal
     * ids); `detail`: the raw technical text behind it (file values, CLI hints), for a Details disclosure.
     */
    Reason: {
      /** Code */
      code: string;
      /** Detail */
      detail: string | null;
      /** Text */
      text: string;
    };
    /** Recommendation */
    Recommendation: {
      change: components["schemas"]["RecommendationChange"] | null;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Severity */
      severity: string;
      /** Title */
      title: string;
      /** Why */
      why: string;
    };
    /** RecommendationChange */
    RecommendationChange: {
      /** File */
      file: string;
      /** From */
      from: unknown;
      /** Path */
      path: string;
      /** To */
      to: unknown;
    };
    /** Registry */
    Registry: {
      /** Flagged */
      flagged: {
        [key: string]: unknown;
      } | null;
      /** Verified */
      verified: {
        [key: string]: unknown;
      } | null;
    };
    /** ResetFailuresBody */
    ResetFailuresBody: {
      /** Kind */
      kind?: ("score" | "prepare" | "apply") | null;
    };
    /** ResponseBreakdown */
    ResponseBreakdown: {
      /** Companies */
      companies: (string | null)[];
      /** Count */
      count: number;
      /** Status */
      status: string;
    };
    /** ResponseRateTile */
    ResponseRateTile: {
      /** Applied */
      applied: number;
      /** Breakdown */
      breakdown: components["schemas"]["ResponseBreakdown"][];
      /** Days */
      days: number;
      /** Definition */
      definition: string;
      /** Rate */
      rate: number | null;
      /** Responded */
      responded: number;
      /** Rows */
      rows: components["schemas"]["TileRow"][];
    };
    /** RunBudget */
    RunBudget: {
      /** Max Jobs */
      max_jobs?: number | null;
      /** Max Minutes */
      max_minutes?: number | null;
      /** Preset */
      preset?: string | null;
    };
    /** RunCap */
    RunCap: {
      /** Applied */
      applied: number;
      /** Base */
      base: number;
      /** Cap */
      cap: number;
      /** Date */
      date: string;
      /** Multiplier */
      multiplier: number;
      /** Reached */
      reached: boolean;
      /** Remaining */
      remaining: number;
    };
    /** RunDetail */
    RunDetail: {
      /** Attempts */
      attempts: components["schemas"]["Attempt"][];
      budget?: components["schemas"]["RunBudget"];
      /** Cmd */
      cmd?: string[];
      /** Counters */
      counters?: {
        [key: string]: number;
      };
      /** Detail */
      detail?: string;
      /** Dry Run */
      dry_run?: boolean;
      /** Duration S */
      duration_s?: number | null;
      /** Ended At */
      ended_at: string | null;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Log */
      log: string;
      /** Pid */
      pid?: number | null;
      /** Started At */
      started_at: string | null;
      /** State */
      state: string;
      /** Status */
      status: string;
      /** Step */
      step?: boolean;
      /** Stop Reason */
      stop_reason: string | null;
      /** Trigger */
      trigger: string;
      /** Warnings */
      warnings?: string[];
    };
    /** RunJobRow */
    RunJobRow: {
      /** Company */
      company: string | null;
      /** Detail */
      detail: string;
      /** Duration S */
      duration_s: number | null;
      /** Job Id */
      job_id: string;
      /** Outcome */
      outcome: string | null;
      /**
       * State
       * @enum {string}
       */
      state: "done" | "failed" | "active" | "queued";
      /** Steps */
      steps: components["schemas"]["JobStep"][];
      /** Title */
      title: string | null;
    };
    /** RunMetrics */
    RunMetrics: {
      /** Attempts */
      attempts: number;
      /** Avg Job S */
      avg_job_s: number;
      /** Budget Used */
      budget_used: number;
      /** Failed */
      failed: number;
      /** Failure Rate */
      failure_rate: number;
      /** P90 Job S */
      p90_job_s: number;
      /** Prepare Share */
      prepare_share?: number | null;
      /** Runs */
      runs: number;
      /** Stops */
      stops: {
        [key: string]: number;
      };
    };
    /** RunPause */
    RunPause: {
      /** Paused At */
      paused_at: string;
      /** Reason */
      reason: string;
      /** Until */
      until: string | null;
    };
    /** RunRecord */
    RunRecord: {
      /** Attempts */
      attempts?: number[];
      budget?: components["schemas"]["RunBudget"];
      /** Cmd */
      cmd?: string[];
      /** Counters */
      counters?: {
        [key: string]: number;
      };
      /** Detail */
      detail?: string;
      /** Dry Run */
      dry_run?: boolean;
      /** Duration S */
      duration_s?: number | null;
      /** Ended At */
      ended_at: string | null;
      /** Id */
      id: string;
      /** Kind */
      kind: string;
      /** Pid */
      pid?: number | null;
      /** Started At */
      started_at: string | null;
      /** State */
      state: string;
      /** Status */
      status: string;
      /** Step */
      step?: boolean;
      /** Stop Reason */
      stop_reason: string | null;
      /** Trigger */
      trigger: string;
      /** Warnings */
      warnings?: string[];
    };
    /** RunRow */
    RunRow: {
      /** Attempted */
      attempted: number | null;
      /** Detail */
      detail: string | null;
      /** Duration S */
      duration_s: number | null;
      /** Ended At */
      ended_at: string | null;
      /** Failed */
      failed: number | null;
      /** Id */
      id: string;
      /** Interrupted */
      interrupted: boolean;
      /** Kind */
      kind: string | null;
      /** Ok */
      ok: number | null;
      /** Started At */
      started_at: string | null;
      /** Status */
      status: string | null;
      /** Stop Reason */
      stop_reason: string | null;
      /** Trigger */
      trigger: string | null;
    };
    /** RunUsed */
    RunUsed: {
      /** Jobs */
      jobs: number;
      /** Max Jobs */
      max_jobs: number | null;
      /** Max Minutes */
      max_minutes: number | null;
      /** Minutes */
      minutes: number | null;
    };
    /** RunsAdvice */
    RunsAdvice: {
      /** Metrics */
      metrics: {
        [key: string]: components["schemas"]["RunMetrics"];
      };
      /** Min Runs */
      min_runs: number;
      /** Ready */
      ready: boolean;
      /** Recommendations */
      recommendations: components["schemas"]["Recommendation"][];
    };
    /** SafetyHint */
    SafetyHint: {
      /**
       * Kind
       * @constant
       */
      kind: "safety";
      /** Text */
      text: string;
    };
    /** Schedule */
    Schedule: {
      catch_up: components["schemas"]["CatchUp"] | null;
      /** Inbox Ready */
      inbox_ready: boolean;
      /** Installed */
      installed: boolean;
      /** Jobs */
      jobs: components["schemas"]["ScheduleJob"][];
      /** Label */
      label: string | null;
      /** Last Tick */
      last_tick: string | null;
      /** Loaded */
      loaded: boolean;
      paused: components["schemas"]["RunPause"] | null;
      quiet_hours: components["schemas"]["QuietHours"] | null;
      /** Tick Minutes */
      tick_minutes: number;
    };
    /** ScheduleJob */
    ScheduleJob: {
      /** At */
      at: string[];
      /** Claude */
      claude: boolean;
      /** Enabled */
      enabled: boolean;
      /** Every Minutes */
      every_minutes: number | null;
      /** Kind */
      kind: string;
      /** Last Run */
      last_run: string | null;
      /** Last Status */
      last_status: string | null;
      /** Next */
      next: string | null;
      /** Preset */
      preset: string | null;
    };
    /** ScheduleState */
    ScheduleState: {
      /** Error */
      error: string | null;
      /** Last Tick */
      last_tick: string | null;
      /** Next */
      next: {
        [key: string]: string | null;
      };
    };
    /** SectionData */
    SectionData: {
      /** Defaults */
      defaults: {
        [key: string]: unknown;
      };
      /** Files */
      files: {
        [key: string]: string;
      };
      section: components["schemas"]["SectionSchema"];
      /** Values */
      values: {
        [key: string]: unknown;
      };
      /** Version */
      version: string;
      /** Warnings */
      warnings: {
        [key: string]: components["schemas"]["UnquotedWarning"];
      };
    };
    /** SectionList */
    SectionList: {
      /** Sections */
      sections: components["schemas"]["SectionSummary"][];
    };
    /** SectionSchema */
    SectionSchema: {
      /** Files */
      files: string[];
      /** Groups */
      groups: components["schemas"]["GroupSchema"][];
      /** Help */
      help: string;
      /** Id */
      id: string;
      /** Title */
      title: string;
    };
    /** SectionSummary */
    SectionSummary: {
      /** Files */
      files: string[];
      /** Help */
      help: string;
      /** Id */
      id: string;
      /** Title */
      title: string;
    };
    /** StartBody */
    StartBody: {
      /**
       * Dry Run
       * @default false
       */
      dry_run?: boolean;
      /** Kind */
      kind: string;
      /** Max Jobs */
      max_jobs?: number | null;
      /** Max Minutes */
      max_minutes?: number | null;
      /** Preset */
      preset?: string | null;
    };
    /** Status */
    Status: {
      /** Catch Up */
      catch_up: {
        [key: string]: unknown;
      } | null;
      counts: components["schemas"]["Counts"];
      index: components["schemas"]["IndexState"];
      /** Now */
      now: string;
      /** Paused */
      paused: {
        [key: string]: unknown;
      } | null;
      pipeline: components["schemas"]["PipelineCounts"];
      /** Recent Runs */
      recent_runs: components["schemas"]["RunRow"][];
      schedule: components["schemas"]["ScheduleState"];
      tiles: components["schemas"]["Tiles"];
    };
    /** StatusBody */
    StatusBody: {
      /** Note */
      note?: string | null;
      /** Status */
      status: string;
    };
    /** StorageAdvice */
    StorageAdvice: {
      /** Budget */
      budget?: number;
      /** Current */
      current?: number;
      /** Days */
      days: number;
      /** Need Days */
      need_days: number;
      projection?: components["schemas"]["Projection"];
      /** Rate Per Day */
      rate_per_day?: number;
      /** Ready */
      ready: boolean;
      /** Recommendations */
      recommendations: components["schemas"]["Recommendation"][];
    };
    /** StorageLimits */
    StorageLimits: {
      /** Budget Mb */
      budget_mb: number;
      /** Disk Free Warn Pct */
      disk_free_warn_pct: number;
      /** Warn At Pct */
      warn_at_pct: number;
    };
    /**
     * StorageSnapshot
     * @description One line of the snapshots log (appended after each run / prune; older lines may lack keys).
     */
    StorageSnapshot: {
      /** At */
      at?: string;
      /** Bytes */
      bytes?: {
        [key: string]: number;
      };
      disk?: components["schemas"]["DiskUsage"];
      /** Pruned Bytes */
      pruned_bytes?: number | null;
      /** Total */
      total: number;
      /** Trigger */
      trigger?: string;
    };
    /**
     * StorageView
     * @description GET /api/storage: bytes per category, the disk, the snapshot history and the advisor config.
     */
    StorageView: {
      /** Bytes */
      bytes: {
        [key: string]: number;
      };
      config: components["schemas"]["AdvisorConfig"];
      disk: components["schemas"]["DiskUsage"];
      /** Snapshots */
      snapshots: components["schemas"]["StorageSnapshot"][];
      /** Total */
      total: number;
    };
    /** Submitted */
    Submitted: {
      /** Count */
      count: number;
      /** Since */
      since: string;
    };
    /** TierAHint */
    TierAHint: {
      /**
       * Kind
       * @constant
       */
      kind: "tier_a";
    };
    /** TileRow */
    TileRow: {
      /** Company */
      company: string | null;
      /** Detail */
      detail: string | null;
      /** Job Id */
      job_id: string;
      /** Role */
      role: string | null;
      /** When */
      when: string | null;
    };
    /** Tiles */
    Tiles: {
      applied_week: components["schemas"]["AppliedWeekTile"];
      interviews: components["schemas"]["InterviewsTile"];
      needs_you: components["schemas"]["NeedsYouTile"];
      response_rate: components["schemas"]["ResponseRateTile"];
    };
    /** Today */
    Today: {
      /** Actions */
      actions: components["schemas"]["ActionItem"][];
      prepare_queue: components["schemas"]["PrepareQueue"];
    };
    /** UiSettings */
    UiSettings: {
      /** Due Soon Hours */
      due_soon_hours: number;
      /** Page Size */
      page_size: number;
      /** Pause Until Tomorrow At */
      pause_until_tomorrow_at: string;
      /** Theme */
      theme: string;
      /** Undo Seconds */
      undo_seconds: number;
    };
    /** Unblock */
    Unblock: {
      /** Company */
      company: string;
      /**
       * Remove
       * @default true
       */
      remove?: boolean;
    };
    /** UndoSafe */
    UndoSafe: {
      /** Previous Status */
      previous_status?: string | null;
      /** Registry Before */
      registry_before?: {
        [key: string]: unknown;
      } | null;
    };
    /** UnquotedWarning */
    UnquotedWarning: {
      /** Intended */
      intended: unknown;
      /** Message */
      message: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VerifyBody */
    VerifyBody: {
      /**
       * Domain
       * @default
       */
      domain?: string;
      /**
       * Evidence
       * @default []
       */
      evidence?: string[];
      /**
       * Risk
       * @enum {string}
       */
      risk: "low" | "medium" | "high";
      /**
       * Signals
       * @default []
       */
      signals?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** List Actions */
  list_actions_api_actions_get: {
    parameters: {
      query?: {
        tab?: string;
        group?: string;
        sort?: string;
        tz?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ActionsPage"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Action */
  add_action_api_actions_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewItem"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Bulk Done */
  bulk_done_api_actions_bulk_done_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ids"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Bulk Reopen */
  bulk_reopen_api_actions_bulk_reopen_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Ids"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Answer
   * @description Learn the answer to a question/salary item (profile/standard_answers.yaml + the job's answers.json), then
   * mark it done. Returns the done outcome plus `learned` {key, scope, company, question, answer, match}.
   */
  answer_api_actions__aid__answer_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Answer"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Block Company */
  block_company_api_actions__aid__block_company_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Done */
  done_api_actions__aid__done_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Set Due */
  set_due_api_actions__aid__due_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Due"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mark Safe */
  mark_safe_api_actions__aid__mark_safe_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Undo Mark Safe */
  undo_mark_safe_api_actions__aid__mark_safe_undo_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UndoSafe"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reopen */
  reopen_api_actions__aid__reopen_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Unblock Company */
  unblock_company_api_actions__aid__unblock_company_post: {
    parameters: {
      path: {
        aid: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Unblock"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Advise */
  advise_api_advise_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Advice"];
        };
      };
    };
  };
  /** Advise Apply */
  advise_apply_api_advise__rec_id__apply_post: {
    parameters: {
      path: {
        rec_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create */
  create_api_batches_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Batch"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Detail */
  detail_api_batches__batch_id__get: {
    parameters: {
      path: {
        batch_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Batch"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Contacts */
  list_contacts_api_contacts_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContactsPage"];
        };
      };
    };
  };
  /** Mark Contact */
  mark_contact_api_contacts__job_id___name__mark_post: {
    parameters: {
      path: {
        job_id: string;
        name: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MarkBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Events */
  events_api_events_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** List Inbox */
  list_inbox_api_inbox_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InboxPage"];
        };
      };
    };
  };
  /** Inbox Detail */
  inbox_detail_api_inbox__job_id__get: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InboxDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Jobs */
  list_jobs_api_jobs_get: {
    parameters: {
      query?: {
        status?: string[];
        tier?: string[];
        safety?: string[];
        category?: string[];
        q?: string | null;
        location?: string | null;
        sort?: string;
        cursor?: string | null;
        tab?: string | null;
        limit?: number | null;
        company?: string[];
        location_in?: string[];
        ats?: string[];
        qa_passed?: string[];
        fit_min?: number | null;
        fit_max?: number | null;
        qa_score_min?: number | null;
        qa_score_max?: number | null;
        found_from?: string | null;
        found_to?: string | null;
        applied_from?: string | null;
        applied_to?: string | null;
        closes_from?: string | null;
        closes_to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobsPage"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export */
  export_api_jobs_export_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Export"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Job Facets
   * @description Distinct values of one column with counts under every other active filter (the header filter menu).
   */
  job_facets_api_jobs_facets_get: {
    parameters: {
      query: {
        field: string;
        status?: string[];
        tier?: string[];
        safety?: string[];
        category?: string[];
        q?: string | null;
        location?: string | null;
        tab?: string | null;
        company?: string[];
        location_in?: string[];
        ats?: string[];
        qa_passed?: string[];
        fit_min?: number | null;
        fit_max?: number | null;
        qa_score_min?: number | null;
        qa_score_max?: number | null;
        found_from?: string | null;
        found_to?: string | null;
        applied_from?: string | null;
        applied_to?: string | null;
        closes_from?: string | null;
        closes_to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobFacets"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Job Tabs */
  job_tabs_api_jobs_tabs_get: {
    parameters: {
      query?: {
        status?: string[];
        tier?: string[];
        safety?: string[];
        category?: string[];
        q?: string | null;
        location?: string | null;
        company?: string[];
        location_in?: string[];
        ats?: string[];
        qa_passed?: string[];
        fit_min?: number | null;
        fit_max?: number | null;
        qa_score_min?: number | null;
        qa_score_max?: number | null;
        found_from?: string | null;
        found_to?: string | null;
        applied_from?: string | null;
        applied_to?: string | null;
        closes_from?: string | null;
        closes_to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobsTabs"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Job Detail */
  job_detail_api_jobs__job_id__get: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["JobDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reset Job Failures
   * @description Clear the job's run failure count (`careeros run reset-failures`): a job out of retries runs again. Its
   * out-of-retries Action Items are marked done.
   */
  reset_job_failures_api_jobs__job_id__failures_reset_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ResetFailuresBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Job File */
  job_file_api_jobs__job_id__files__name__get: {
    parameters: {
      path: {
        job_id: string;
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Open Folder */
  open_folder_api_jobs__job_id__open_folder_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Set Override */
  set_override_api_jobs__job_id__override_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OverrideBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Job Pipeline
   * @description The job's stage, the one next action (Start / Continue / Approve & continue), why it is blocked, what a
   * needs_review job waits on, and the running run that names it.
   */
  job_pipeline_api_jobs__job_id__pipeline_get: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineState"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Start Job Pipeline
   * @description Run the job's next stage as a detached `careeros run <kind> --job <id>`; approve_continue first moves
   * needs_review -> queued. 409 when a run is active or paused, or the job is not runnable (Tier A never applies).
   */
  start_job_pipeline_api_jobs__job_id__pipeline_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PipelineBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PipelineStarted"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Rerun Qa */
  rerun_qa_api_jobs__job_id__qa_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Safety Clear */
  safety_clear_api_jobs__job_id__safety_clear_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ClearBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Safety Flag */
  safety_flag_api_jobs__job_id__safety_flag_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FlagBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Safety Verify */
  safety_verify_api_jobs__job_id__safety_verify_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Set Status */
  set_status_api_jobs__job_id__status_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StatusBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Mark Submitted */
  mark_submitted_api_jobs__job_id__submitted_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["NoteBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Withdraw */
  withdraw_api_jobs__job_id__withdraw_post: {
    parameters: {
      path: {
        job_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["NoteBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Lessons */
  list_lessons_api_learning_lessons_get: {
    parameters: {
      query?: {
        ats?: string | null;
        company?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Lessons"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Add Lesson */
  add_lesson_api_learning_lessons_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewLesson"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Lesson"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Meta */
  meta_api_meta_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
    };
  };
  /** Board */
  board_api_pipeline_get: {
    parameters: {
      query?: {
        tier?: string[];
        category?: string[];
        safety?: string[];
        location?: string[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Board"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Prune */
  prune_api_prune_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PruneBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** History */
  history_api_runs_get: {
    parameters: {
      query?: {
        kind?: string | null;
        cursor?: string | null;
        limit?: number | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HistoryPage"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Start
   * @description A score or prepare batch; `dry_run` returns the selection and starts nothing.
   */
  start_api_runs_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartBody"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Cancel */
  cancel_api_runs_cancel_post: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CancelBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Catch Up */
  catch_up_api_runs_catch_up_post: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["CatchUpBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Current */
  current_api_runs_current_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CurrentRun"] | null;
        };
      };
    };
  };
  /** Pause */
  pause_api_runs_pause_post: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PauseBody"] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Queue */
  queue_api_runs_queue__kind__get: {
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        kind: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Resume */
  resume_api_runs_resume_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Start Step */
  start_step_api_runs_steps__kind__post: {
    parameters: {
      path: {
        kind: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Detail */
  detail_api_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Stream
   * @description SSE: `event` frames ({type, text, attempt?}) from the attempt streams and run.log, then one `end` frame
   * ({state, stop_reason}) when the run is no longer running. A reconnect replays from the start.
   */
  stream_api_runs__run_id__stream_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Schedule */
  schedule_api_schedule_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Schedule"];
        };
      };
    };
  };
  /** Schedule Action */
  schedule_action_api_schedule__action__post: {
    parameters: {
      path: {
        action: "install" | "uninstall";
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Sections */
  sections_api_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SectionList"];
        };
      };
    };
  };
  /** Ranking Preview */
  ranking_preview_api_settings_runs_ranking_preview_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Preview"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Read */
  read_api_settings__section__get: {
    parameters: {
      path: {
        section: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SectionData"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Save */
  save_api_settings__section__put: {
    parameters: {
      path: {
        section: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Changes"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Diff */
  diff_api_settings__section__diff_post: {
    parameters: {
      path: {
        section: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Changes"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reset */
  reset_api_settings__section__reset__group__post: {
    parameters: {
      path: {
        section: string;
        group: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Status */
  status_api_status_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Status"];
        };
      };
    };
  };
  /** Storage */
  storage_api_storage_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StorageView"];
        };
      };
    };
  };
  /** Today */
  today_api_today_get: {
    parameters: {
      query?: {
        tz?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Today"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Open Tracker */
  open_tracker_api_tracker_open_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Sync */
  sync_api_tracker_sync_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
